### PR TITLE
Reuse WebView to response appcontrol request

### PR DESCRIPTION
**Pull request by myroot**
- Issue
  - WebView re-create was cause re-create renderer process
  - Re-creation of WebView was take a long time
- Proposal
  - Reuse WebView(just change the URL of current WebView)

### CODE REVIEW

**Comment by WonyoungChoi** [comment]
LGTM

**Comment by myroot** [comment]
-1
It has a bug with mult-window

**Comment by myroot** [comment]
multi-window related bug was fixed

**Comment by WonyoungChoi** [comment]
merge conflict. please rebase this commit again.

**Comment by myroot** [comment]
Rebased

**Pull request merged**
