### PR TITLE
config.xml parameter change: on-reset -> reload

### PR DESCRIPTION
**Pull request by psikorski**
Depends on: https://review.tizen.org/gerrit/#/c/48171/

### CODE REVIEW

**Comment by psikorski** [comment]
it must be submitted after https://review.tizen.org/gerrit/#/c/48171/  merge (and gbs submit)

**Comment by WonyoungChoi** [comment]
LGTM, 

It seems that this PR should be group submitted together with https://review.tizen.org/gerrit/#/c/48171/.

If you let me know the submission tag of the commit when merged, I'll SR together.

**Comment by WonyoungChoi** [comment]
And more tips,
Please make your branch in your forked repository before works for PR to this project. 
eg. "change_reset_attr" 
It is more useful and safe method in github.

**Comment by psikorski** [comment]
thanks for the tip. I'll do that

**Pull request merged**
