### PR TITLE
Adjust DynamicPlugin* funtions to library version 1

### PR DESCRIPTION
**Pull request by mniesluchow**
Along with ewk_context_tizen_app_id_set function introduction
by chromium-efl, newer version of DynamicPlugin library has been
provided. See sample file ([1]) of chromium-efl ([2]) repository.

[1] tizen_src/ewk/unittest/resources/ewk_context/injected_bundle/chromium/bundle_sample.cc
[2] https://review.tizen.org/gerrit/#/admin/projects/platform/framework/web/chromium-efl

### CODE REVIEW

**Comment by WonyoungChoi** [comment]
This commit seems like have a dependency with the chromium-efl. Don't you need group submission with it?

**Comment by mniesluchow** [comment]
What do you mean? I may not be aware of development process of crosswalk-tizen. If this is not the way, then please show me some guideline I should refer to.

**Comment by myroot** [comment]
Please, let me know. why this changes need more details. 
- chromium-efl commit id
- What is mean returing value in DynamicPluginVersion

**Comment by WonyoungChoi** [comment]
@mniesluchow  As you know, this commit has dependencies with the chromium-efl. So this commit should be merged and applied to Tizen binary with the chromium-efl's changes together.
Therefore, I want to know the status of the chromium-efl' changes related with this commit.

**Comment by WonyoungChoi** [comment]
I've verified this PR. It works well with the latest chromium efl.

**Comment by WonyoungChoi** [comment]
LGTM

**Pull request merged**
